#!/usr/bin/env bash
# Fail if product paths teach removed CLI namespaces or old crate paths.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail=0
scan() {
  local pattern="$1"
  local hits
  hits=$(grep -rnE "$pattern" \
    src/ods-core src/ods-cli src/scripts \
    docs/guide docs/other-specs docs/maintainer \
    README.md AGENTS.md CONTRIBUTING.md \
    --include='*.rs' --include='*.md' --include='*.sh' --include='*.ps1' --include='*.yml' \
    2>/dev/null | \
    grep -v 'src/scripts/check-naming.sh' | \
    grep -vE 'never use|hard-removed|no `ods|no namespace|flags only|prefer|Prefer|`--okf`|do not invent|legacy|namespace \(|flag-only|Removed|historical|cli-multi-spec|product surface|unknown command: okf|must fail|SMOKE|Generated by|educational' | \
    grep -v 'ods okf lint "${OKF}"' || true)
  if [ -n "$hits" ]; then
    echo "NAMING GATE FAIL: pattern=$pattern"
    echo "$hits"
    fail=1
  fi
}

scan 'ods okf '
scan 'ods ods '
scan 'src/crates/'

if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "check-naming: OK"
